#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../scripts/_env"

CONFIGURATION=$(readlink --canonicalize "$ROOT/configuration/ssh")

cat "$CONFIGURATION/ssh.config.template" | IP=$IP HERE=$CONFIGURATION envsubst > "$CONFIGURATION/ssh.config"
