#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../scripts/_env"
. "$ROOT/scripts/_trap"

minikube profile edge

IMAGE=asterisk-cnf
LOCAL=localhost/$IMAGE
REMOTE=docker://$(minikube ip):5000/$IMAGE

skopeo delete --tls-verify=false "$REMOTE" || true
buildah push --tls-verify=false "$LOCAL" "$REMOTE"
