#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../scripts/_env"
. "$HERE/_env"

cat "$ROOT/configuration/linphone/linphonerc-200.template" | \
IP=$IP NAT_IP=$LIBVIRT_GATEWAY envsubst > "$ROOT/configuration/linphone/linphonerc-200"
