#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../scripts/_env"

if [ "$1" == -c ]; then
	"$HERE/delete-edge"
fi

. "$HERE/_env"

minikube profile edge

IP_PREFIX=$EDGE_IP_PREFIX \
kubectl_apply_template "$ROOT/configuration/kubernetes/data-plane.yaml"
