#!/bin/bash
set -e

LIBYANG_VERSION=v1.0.184
LIBNETCONF_VERSION=v1.1.26
SYSREPO_VERSION=v1.4.70
NETOPEER2_VERSION=v1.1.39

dnf --assumeyes install \
	tcpdump grc \
	git cmake make gcc gcc-c++ swig openssl \
	libcurl-devel libssh-devel openssl-devel pcre-devel python3-devel \
	libcmocka-devel doxygen groff-perl

dnf --assumeyes clean all

# optional: libcmocka-devel is to enable tests
# optional: doxygen, groff-perl are for generating documentation

function build () {
	local DIR=$1
	mkdir "$DIR/build"
	pushd "$DIR/build" > /dev/null
	cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr "${@:2}"
	make --jobs=$(nproc)
	make install
	popd > /dev/null
	rm --recursive --force "$DIR"
}

function user () {
	useradd --system --no-create-home --shell /sbin/nologin "$1"
}

cd /tmp

# libssh (Fedora 32 contains libssh-devel version 0.9 that does not work with libnetconf)
# requires: zlib-devel, openssl-devel
#git clone --branch libssh-0.8.8 https://git.libssh.org/projects/libssh.git
#build libssh

# libcurl (Fedora 32 contains libcurl-devel version 7.69 that does not work with netopeer2)
#git clone --branch curl-7_61_1 https://github.com/curl/curl.git
#build curl
#cp /usr/lib/libcurl.so /usr/lib64/

# libyang
# requires: pcre-devel, python3-devel, swig
git clone --branch $LIBYANG_VERSION https://github.com/CESNET/libyang.git
build libyang -DGEN_LANGUAGE_BINDINGS:BOOL=ON

# libnetconf2
# requires: openssl-devel, libssh-devel, libyang (above)
git clone --branch $LIBNETCONF_VERSION https://github.com/CESNET/libnetconf2.git
build libnetconf2

# sysrepo
# requires: libyang (above), python3-devel, swig
git clone --branch $SYSREPO_VERSION https://github.com/sysrepo/sysrepo.git
build sysrepo -DGEN_LANGUAGE_BINDINGS:BOOL=ON -DREPO_PATH:PATH=/etc/sysrepo

# netopeer2
# requires: libcurl-devel, libssh-devel, openssl, libyang (above), libnetconf2 (above), sysrepo (above)
git clone --branch $NETOPEER2_VERSION https://github.com/CESNET/Netopeer2.git
build Netopeer2 -DGEN_LANGUAGE_BINDINGS:BOOL=ON

# sysrepo-plugind.service
user sysrepo
mkdir --parents /usr/lib64/sysrepo/plugins
chown sysrepo:sysrepo --recursive /usr/lib64/sysrepo/plugins
cat > /etc/systemd/system/sysrepo-plugind.service <<- EOT
	[Unit]
	Description=sysrepo-plugind

	[Service]
	Type=forking
	User=sysrepo
	ExecStart=/usr/bin/sysrepo-plugind -v 1

	[Install]
	WantedBy=multi-user.target
EOT
chmod 0644 /etc/systemd/system/sysrepo-plugind.service

# netopeer2-server.service
user netopeer
cat > /etc/systemd/system/netopeer2-server.service <<- EOT
	[Unit]
	Description=netopeer2-server

	[Service]
	Type=forking
	PIDFile=/run/netopeer2-server.pid
	ExecStart=/usr/bin/netopeer2-server -v 1 -u netopeer -g netopeer

	[Install]
	WantedBy=multi-user.target
EOT
chmod 0644 /etc/systemd/system/netopeer2-server.service

systemctl daemon-reload
systemctl start netopeer2-server.service
systemctl enable netopeer2-server.service

#systemctl start sysrepo-plugind.service
#systemctl enable sysrepo-plugind.service

# This allows Fedora to use the old "ssh-rsa" algorithm for libssh
# (Unfortunately, Python clients that rely on Paramiko do not yet support newer algorithms)
update-crypto-policies --set LEGACY

echo Done!
