
Vagrant.configure("2") do |config|
  config.vm.define "sysrepo"
  config.vm.box = "fedora/31-cloud-base"
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 4
    libvirt.memory = 2048
  end
  config.vm.provision :shell, path: "install"
  config.vm.network :forwarded_port, guest: 830, host: 8300
end
