#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../scripts/_env"

minikube profile central

"$ROOT/ssh/ssh" -t asterisk-vnf 'cd / &&' sudo -u asterisk asterisk -rvvvvvvv "$@"
