#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../../scripts/_env"
. "$ROOT/scripts/_trap"

minikube profile central

m "deleting Asterisk VNF from namespace \"$WORKSPACE\"..."

kubectl_delete_template "$ROOT/configuration/kubernetes/asterisk-vnf.yaml"
